### ISSUE TITLE
How do I use livereload with `build`

### ISSUE THREAD

**Issue by cameronmcefee** [RobertDeRose/jekyll-livereload#10]
Hello!

From [looking through this repo](https://github.com/RobertDeRose/jekyll-livereload/blob/master/lib/jekyll-livereload/build.rb), it seems that livereload should work when using `build` rather than `serve`. Is that correct? However, if I get it working with `serve` and then run `build` instead, it doesn't appear to work.

I noticed [here](https://github.com/RobertDeRose/jekyll-livereload/blob/master/lib/jekyll-livereload/build.rb#L12) that it's looking for some sort of `serving` option. Where is that supplied? Is that a config value that needs to be set, or is that some jekyll internal option?

To explain my usecase, I'm using Jekyll in combination with Firebase. Firebase provides their own local server environment which adds some firebase specific stuff, so I'm running jekyll with `build --watch` and serving the compiled output with the firebase server.

**Comment by RobertDeRose** [comment]
This is just for development, it's a plugin specifically for the included server, it doesn't really make sense to work with just the build command. In fact it was opened as a a bug that it was included when just build was called.  The plugin would have to be modified to support the build function and check for the `--watch` option and only include then, but even that would be iffy behavior.

**Comment by cameronmcefee** [comment]
👍 Thanks for clarifying.
