### ISSUE TITLE
Readme.md doesn't explain what livereload is/does.

### ISSUE THREAD

**Issue by rolfedh** [RobertDeRose/jekyll-livereload#13]
Would you add a summary explanation of livereload to the introduction? Something that helps non-developers quickly understand what it is and why they might want to use it with Jekyll.

**Comment by rolfedh** [comment]
If you draft some preliminary content, I'll be happy to review/edit it.

**Comment by RobertDeRose** [comment]
OK that sounds far

**Comment by johnpitchko** [comment]
I also encountered this issue. Freely admit that I am a noob. A simple link to the livereload.com or to their repo is probably all that is needed.

**Comment by nocke** [comment]
...or [take from the discussion, that led to it](https://github.com/jekyll/jekyll/issues/4644)?
