### ISSUE TITLE
Page not refreshing

### ISSUE THREAD

**Issue by DougBeney** [RobertDeRose/jekyll-livereload#14]
Hello, I've been using your plugin for quite some time. I just attempted to use this plugin today (Haven't used it in a month or two) and ran into a problem. My site displays fine, but when I make a change to a file (whether it be an HTML file, Pug file, Sass file, or CSS), my page does not automatically refresh. 

In the terminal, I can see that Jekyll rebuilds my project though, and of course if I manually refresh the page, I will see the change.

Here is my project: https://github.com/DougBeney/J5

Bundler version 1.16.0
jekyll 3.6.2
Using jekyll-livereload 0.2.2

**Comment by RobertDeRose** [comment]
i'll take a look asap

**Comment by RobertDeRose** [comment]
I got this to work work once I figured out that I had to install Pug.

```bash
git clone https://github.com/DougBeney/J5.git
npm install -g pug-cli
bundle install --path vendor/bundle
cat <<EOF >> _config.yml

exclude:
    - vendor/
EOF


bundle exec jekyll serve
Configuration file: /Users/rderose/workspace/ruby/J5/_config.yml
Configuration file: /Users/rderose/workspace/ruby/J5/_config.yml
            Source: src
       Destination: dist
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.034 seconds.
 Auto-regeneration: enabled for 'src'
 LiveReload Server: http://127.0.0.1:35729
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
        LiveReload: Browser connected
```

**Comment by DougBeney** [comment]
I have pug-cli already. Everything renders fine, the problem is that my page does not automatically reload when I make a change to a file. 

Could have something to do with my OS - Ubuntu 17.10. Any ideas on how I could troubleshoot the page/livereload server to figure out why it isn't refreshing?

**Comment by RobertDeRose** [comment]
Are you running in a VM or something?

**Comment by DougBeney** [comment]
Nope. My laptop.

**Comment by RobertDeRose** [comment]
Let me try installing an Ubuntu VM and see what if any issues I get

**Comment by DougBeney** [comment]
Appreciate the effort, Robert. Looking forward to your findings. It could always be something with Ubuntu 17.10. Quite a bit different compared to Ubuntu 16.04.

**Comment by RobertDeRose** [comment]
OK... Here is what I just attempted and had no issues...

```
vagrant init bento/ubunut-17.10
sed -i "" /end/d Vagrantfile
cat <<EOF >> Vagrantfile
  config.vm.network "forwarded_port", guest: 4000, host: 4000
  config.vm.network "forwarded_port", guest: 35729, host: 35729
end
EOF
```

Then I ssh'ed into the VM:

```
vagrant ssh
```

Once inside the VM

```
sudo apt-get install -y git ruby ruby-dev npm
sudo gem install bundler
sudo npm -g install pug

git clone https://github.com/DougBeney/J5.git
cd J5

bundle install --path vendor/bundle
cat <<EOF >> _config.yml

exclude:
    - vendor/
EOF

bundle exec jekyll serve --host 0.0.0.0
```

Now on my local machine I can open a browser to `http://localhost:4000` and then edit the `J5/src/index.pug` file and whenever I save the file, it reloads, really fast too, even faster than when running locally on my Mac, which is a little weird.

Something I noticed personally though, I am using VMWare Fusion for VMs on my Mac, I can't edit the files locally on the mac, it for whatever reason doesn't notify the Linux Kernel that the file has been modified, something could just be missing in my Vagrantfile, or the way Jekyll watches files, or something. But all edit on the VM, trigger the Livereload as expected.

**Comment by RobertDeRose** [comment]
@DougBeney I'm going to close this issue since I have not heard back from you in a while and I was not able to reproduce your issue

**Comment by DougBeney** [comment]
Sorry, must've missed the first email. I'll re-open this issue if I could find a way to reproduce this problem. For now, leaving it closed is fine.
