### ISSUE TITLE
LiveReload not working on new project

### ISSUE THREAD

**Issue by johnpitchko** [RobertDeRose/jekyll-livereload#16]
I'm guessing that this is a similar issues to #1 so opening a new issue as that one is closed. I know the folks in that thread were not super helpful with providing info necessary for troubleshooting. I will do my best here.

Issue is same as in #1; I followed instructions to add jekyll-livereload as a plugin to my Gemfile. When I launch Jekyll server and navigate to the website (localhost:4004), the page does not live reload after I save changes to a source file. Jekyll does successfully regenerate the site (as you can see in the log).

When I navigate to the LiveReload server (localhost:4004), I receive error `This port only serves livereload.js over HTTP.`

Installed jekyll-livereload gem onto an existing Jekyll site. I did this with another jekyll site I manage, so I know it works/worked.

OS: macOS High Sierra 10.13.1
Ruby Version: 2.4.1p111
Jekyll Version: 3.6.2
Gemfile: below
```
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem 'jekyll-livereload'
   gem 'jekyll-sitemap'
   gem 'jekyll-seo-tag'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

Jekyll Serve: below
```
$ bundle exec jekyll serve
Configuration file: /Users/johnpitchko/Sites/haskyane-mba-alumni-jekyll/_config.yml
            Source: /Users/johnpitchko/Sites/haskyane-mba-alumni-jekyll
       Destination: /Users/johnpitchko/Sites/haskyane-mba-alumni-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.833 seconds.
 Auto-regeneration: enabled for '/Users/johnpitchko/Sites/haskyane-mba-alumni-jekyll'
 LiveReload Server: http://127.0.0.1:35729
    Server address: http://127.0.0.1:4004/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2017-12-04 15:12:59 ...done in 0.265965 seconds.
```

What additional information do you require?

**Comment by RobertDeRose** [comment]
I don't see the command line switch to actually enable live reload, either -L, or --livereload is required or your `_config.yml` must contain 

```yaml
# Server Config options
livereload: true     # You no longer need to include --livereload
```

**Comment by RobertDeRose** [comment]
The default port for live reload is 35729, so you would have to connect to `http://127.0.0.1:35729` but you don't actually do that, the live reload script does it

**Comment by RobertDeRose** [comment]
You will also see this embedded in your pages' header 


```html
<script src="https://127.0.0.1:8081/livereload.js"></script>
```
if you inspect the a page being served.

Once you load the page, you should see the following in the your shell

```
        LiveReload: Browser connected
```

**Comment by RobertDeRose** [comment]
I've just attempted  using your `Gemfile` as well and it works as expected.  What browser are you using?  What is not working?  When you edit a file and save it, does the site not reload?

**Comment by johnpitchko** [comment]
Wow would you believe it mysteriously started working today? I did have the `livereload: true` set in my _config.yml.

Anyways will try it again before I close the issue.

**Comment by roytanjx** [comment]
Hey guys, I'm on windows 10, running into a livereload issue with Jekyll where my site does not reload automatically, or detect changes when I refresh the browser manually at

```http://127.0.0.1:4000```

. It only refreshes when I stop and then restart the server, this makes it difficult to see changes almost immediately. I can see that  it's installed

 ```Using jekyll-livereload 0.2.2``` 

and

```gem install jekyll-livereload
Successfully installed jekyll-livereload-0.2.2
Parsing documentation for jekyll-livereload-0.2.2
Installing ri documentation for jekyll-livereload-0.2.2
Done installing documentation for jekyll-livereload after 0 seconds
1 gem installed.```

```
PS C:\WINDOWS\system32> gem -v
2.7.7
PS C:\WINDOWS\system32> jekyll -v
jekyll 3.8.3
PS C:\WINDOWS\system32> ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
```

I have tried reinstalling gems, reinstalling ruby, restarting console and pc, npm http-server,  jekyll serve --incremental, livereload:true and these:

https://github.com/RobertDeRose/jekyll-livereload/issues/1
https://github.com/jekyll/jekyll/issues/4644

When I run bundle exec jekyll serve --livereload, I see this:

```Configuration file: F:/xxxxx/_config.yml
            Source: F:/xxxxx
       Destination: F:/xxxxx/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 5.067 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'F:/xxxxx'
 LiveReload Server: http://127.0.0.1:35729
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.```

 ```http://127.0.0.1:35729```

just shows

```This site can't be reached
127.0.0.1 refused to connect.```

Then I tried

 ```netsh http add iplisten 127.0.0.1
IP address successfully added```

But I'm still getting the same issue.

Any ideas?

**Comment by RobertDeRose** [comment]
@roytanjx this project is now dead since Jekyll now includes live reload in its core. Please use the latest version of Jekyll.
