### ISSUE TITLE
how to serve livereload.js over https

### ISSUE THREAD

**Issue by kosirm** [RobertDeRose/jekyll-livereload#17]
I would like to serve livereload.js over https. I'm using cloud 9, so I only have ports 8080 and 8081 available.
I don't know where to find certificates, etc.

`Mixed Content: The page at 'https://****' was loaded over HTTPS, but requested an insecure script 'http://0.0.0.0:8081/livereload.js'. This request has been blocked; the content must be served over HTTPS.`

**Comment by RobertDeRose** [comment]
First you need a key and cert, you can make one with something like this:

```
openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
```


Then when you enable HTTPS in Jekyll, Livereload will serve over https as well. 

Here is an example, I am using Bundler to vendor my gems, FYI:

```
bundler exec jekyll serve --ssl-cert ./certificate.pem --ssl-key ./key.pem -R 8081 -P 8080
```

This give the following output on the shell

```
Auto-regeneration: enabled for '/Users/rderose/workspace/developers'
 LiveReload Server: https://127.0.0.1:8081
  JekyllAdmin mode: production
    Server address: https://127.0.0.1:8080//
  Server running... press ctrl-c to stop.
        LiveReload: Browser connected
```

Then in your Jekyll site, Livereload will have added the following in your page's header

```
<script src="https://127.0.0.1:8081/livereload.js"></script>
```

**Comment by kosirm** [comment]
Thanks a lot for this excelent explanation with example and everything! 🥇

**Comment by RobertDeRose** [comment]
I'll have to include it in the readme
