### ISSUE TITLE
Jekyll build includes livereload script tag

### ISSUE THREAD

**Issue by peteobrien** [RobertDeRose/jekyll-livereload#2]
(at least when it's default for me) Maybe not a bug per se but Readme could advise around it

p.s. Thanks for the plugin

**Comment by RobertDeRose** [comment]
Not sure what you are talking about here, could you clarify so that I can update the README to what you are talking about?

**Comment by peteobrien** [comment]
OK, sorry, so what I was talking about was, when I built the site (my first jekyll site) it deployed with the `<script src="http://127.0.0.1:35729/livereload.js"></script>` still in the head, I think because I set livereload to default via the config. In the readme, you say `If you always what to use Livereload, **and why wouldn't you**` I think you may not want to set it as default so you don't need to remember to remove it when you build. Does that make sense?

**Comment by RobertDeRose** [comment]
Interesting, might be a bug, I'll have to take a look at that. To be honest, I don't think I ever tested what happens if I just issue the Jekyll build command, the way I wrote the plugin, it should, so I thought, only care about the extra options for the server command, not any other command.

Thanks for the detailed explanation, I will check it out as soon as I can.

**Comment by peteobrien** [comment]
Yep, just tested it. When default `jekyll build` adds livereload to head and when not default it doesn't.

Thanks for the plugin, makes it nice and easy to get livereload working.

**Comment by RobertDeRose** [comment]
OK, so I need an if statement somewhere, :) thanks for the feedback, I'll get a new version out over the weekend if I can. And you are welcome for the plugin!

**Comment by RobertDeRose** [comment]
@peterobrien sorry for the long delay, it wasn't a hard fix, just didn't have the time to do it until now. Thanks again for reporting the issue.
