### ISSUE TITLE
Scroll down on reload

### ISSUE THREAD

**Issue by AllanWang** [RobertDeRose/jekyll-livereload#21]
Is there any chance to add a configuration to automatically scroll to the bottom with each reload? A lot of the times, I'm editing contents at the bottom of a page. This could be as simple as a onready listener, but something that can be toggled and enabled only for live reloads.

**Comment by RobertDeRose** [comment]
This sounds out-side of the scope of this project to me, personally. When I do this in Safari, a reload brings me back to the same spot I was on previously, so it might be something your browser isn't doing or you could add this to your own source while in development.

**Comment by AllanWang** [comment]
Thanks. I think the issue is related to mathjax loading matrices, so the page loaded is smaller than the actual page after formatting.
