### ISSUE TITLE
Doesn't work with --host 0.0.0.0

### ISSUE THREAD

**Issue by adamhammes** [RobertDeRose/jekyll-livereload#4]
My typical workflow is to ssh into my Digitalocean droplet, then serve the site with

```
$ jekyll serve --livereload --host 0.0.0.0
```

Then I can navigate to `$my_droplet_IP:4000` to see what is being served.

However, this setup means the script tag injected by `jekyll_livereload` is as follows:

```
<script src="http://0.0.0.0:35729/livereload.js"></script>
```

Which obviously doesn't work.

If you think that this is something that can be/is worth of being fixed and have some ideas on the *how*, I'd love to take a stab at this issue.

**Comment by RobertDeRose** [comment]
This isn't really an issues that Livereload can handle, you should be using the $my_droplet_ip for the `--host` option and it would work fine.  Just change the order of your operations and your good.

**Comment by adamhammes** [comment]
Ah, I feel dumb now. Thank you!

**Comment by RobertDeRose** [comment]
@adamhammes no worries, glad it works now for you
