### ISSUE TITLE
Option to determine host to use

### ISSUE THREAD

**Issue by everflux** [RobertDeRose/jekyll-livereload#5]
It would be great if there was an option to let live reload use the document hostname property instead of using the IP 0.0.0.0.
Use case: Connecting with multiple devices, f.e. tablet or smart phone, externally.

**Comment by RobertDeRose** [comment]
@everflux It already does :)

https://github.com/RobertDeRose/jekyll-livereload/blob/master/lib/jekyll-livereload/build.rb#L36

It uses the host option passed in when you configure the server, which, defaults to 0.0.0.0
